services:
  - type: web
    name: etudia-v41-api
    env: node
    buildCommand: cd react-app/backend && npm install
    startCommand: cd react-app/backend && npm start
    plan: free
    rootDir: react-app/backend
    envVars:
      - key: NODE_ENV
        value: production
